name: glacier-app
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - param
  - pyviz_comms
  - datashader
  - bokeh
  - holoviews
  - geoviews
  - panel
  - pytables
  - pip:
    - jupyter-panel-proxy
